name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [16, 14, 12]
    name: Run tests on Node.js ${{ matrix.node-version }}
    steps:
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint
      - name: Run audit
        run: npm audit
      - name: Run auditjs
        run: npm run scan